In [143]:
import tabula
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [224]:
stations = pd.read_excel("mtr_station.xlsx")
stations = stations["station"].unique()

In [204]:
file = "ctn_20220127.pdf"

pages = tabula.read_pdf_with_template(f"cache/{file}", template_path="t2.json", lattice=True, pandas_options={'header': None})

df = pd.DataFrame()
for page in pages:
    page = page.astype(str)
    dc = [page[col].str.contains("Specified place").any() for col in page.columns]
    df = pd.concat([df, page.loc[:, dc]], ignore_index=True).astype(str)
# df

In [205]:
df_merge = pd.DataFrame()

for col in df.columns:
    df_merge = pd.concat([df_merge, df.fillna("na")[col].str.contains(r"[^\x00-\x7F]", regex=True)], axis=1)
# df_merge

In [206]:
t1 = df[df_merge.any(axis=1)]

In [225]:
t1[1].apply(lambda y: any(station in y for station in stations))

1      False
2      False
3      False
5      False
13     False
14      True
17     False
22     False
23     False
24     False
26     False
34     False
35      True
36      True
37      True
38     False
39     False
40     False
41     False
42     False
49      True
50     False
51     False
52     False
53     False
54     False
55     False
56     False
63      True
64      True
65      True
66      True
67     False
68     False
69     False
70     False
77     False
78      True
79      True
80      True
81     False
82     False
83     False
84     False
91      True
92      True
93      True
94     False
95     False
96     False
97     False
104    False
105    False
106    False
107    False
108    False
Name: 1, dtype: bool

In [207]:
max_len = t1.apply(lambda y: max(map(len, y)), axis=1)

In [208]:
df_merge = pd.DataFrame()
for col in t1.columns:
    df_merge = pd.concat([df_merge, t1[col].str.len() == max_len], axis=1)
df_merge.columns = t1.columns

In [209]:
t2 = t1[df_merge].apply(lambda y: "".join(y.dropna()), axis=1).str.replace(r"\r|\s|nan|Specified place", "", regex=True)

In [210]:
df_merge = t2.str.contains(r"[A-Za-z]", regex=True)

In [211]:
t3 = t2[df_merge].reset_index(drop=True)

In [212]:
t3.str.replace(r"é|’", "", regex=True).str.extract(r"(.*[^\x00-\x7F]\)?)")

                                            0
0         2022-01-22~2022-01-26(曾身處指明場所超過兩小時)
1                    如意洗衣廠有限公司屯門建旺街4號利通工業大廈5樓
2                      喆麗控股有限公司葵涌葵昌路KC1008樓C室
3         2022-01-21~2022-01-25(曾身處指明場所超過一小時)
4         2022-01-21~2022-01-27(曾身處指明場所超過兩小時)
5                     新輝(建築管理)有限公司灣仔新鴻基中心42樓
6         2022-01-21~2022-01-25(曾身處指明場所超過一小時)
7                             真味鮮廚將軍澳海悅豪園商場地下
8                       保良局第一張永慶中學慈雲山蒲崗村道173號
9   彩雲(一)邨(包括商場)(所有涉及街道清理及公共衞生、和樓宇保安及清潔的工作人員)
10        2022-01-21~2022-01-24(曾身處指明場所超過一小時)
11        2022-01-11~2022-01-27(曾身處指明場所超過兩小時)
12               四洲美利飲食有限公司屯門天后路18號南豐工業城第五座7樓
13        2022-01-21~2022-01-26(曾身處指明場所超過兩小時)
14            坤香園貿易有限公司荃灣橫龍街17-33號明華工業大廈11樓C室
15        2022-01-21~2022-01-24(曾身處指明場所超過兩小時)
16        2022-01-19~2022-01-24(曾身處指明場所超過兩小時)
17        2022-01-17~2022-01-27(曾身處指明場所超過兩小時)
18                   嘉濤耆樂苑屯門井財街7號力生大廈地下8-12號鋪
19        2022-01-20~2022-01-27(曾身處指明場所超過兩小時)
20                長沙灣副食品批發市場(蔬菜市場部份)九龍欽洲街西36號
21        2022-01-14~2022-01-27(曾身處指明場所超過兩小時)
22                                   沙田博康邨博逸樓
23                                   沙田博康邨博泰樓
24        2022-01-14~2022-01-27(曾身處指明場所超過兩小時)
25        2022-01-14~2022-01-27(曾身處指明場所超過1小時)

In [ ]:
df_merge = page.dropna(how="all") \
    .apply(lambda y: "".join(y.dropna().astype(str)), axis=1) \
    .str.replace(r"\r|\s|’|é|及|或|指明地點|視情況而|年年年年", "", regex=True) \
    .str.extract(r"([^\x00-\x7F]+[\s\d\w\(\)-]{0,}[^\x00-\x7F]+[\s\d\w\(\)-]{0,}[^\x00-\x7F]+[\)]{0,})") \
    .dropna() \
    .set_axis(["specified_place"], axis=1)

In [52]:
page.loc[:, dc].apply(lambda y: "".join(y.dropna().astype(str)), axis=1)

0            指明地點\rSpecified place指明地點\rSpecified place
1                                (視情況而定任何一個[年年年年-月月-日日]
2                                                期間及時段)
3                                          [年年年年-月月-日日]
4                                     Specified date(s)
5                                    and time period(s)
6                                 (Any of the specified
7                            date(s) and time period(s)
8                                        as applicable)
9                                          [YYYY-MM-DD]
10    銅鑼灣恩平道28 號利\r園二期10樓如新生活體\r驗館\rNUSKINPlaza,10/F...
11    青衣青敬路33 號青衣\r城一期 3樓 301號鋪肯\r德基\rKFC, Shop 301,...
12    將軍澳唐德街 1 號將軍\r澳廣場 1 樓 1-004 號鋪\r太興\rTaiHing,Sh...
dtype: object

In [ ]:
"".join(y.dropna().astype(str)

In [30]:
file = "ctn_20220114.pdf"
pages = tabula.read_pdf_with_template(f"cache/{file}", template_path="t1.json", lattice=True, pandas_options={'header': None})
# pages = tabula.read_pdf(f"cache/{file}", lattice=True, pages="all")
df = pd.DataFrame()
for page in pages:
    df = pd.concat([df, page], ignore_index=True)
    display(page)
df

,0,1,2,3,4,5,6,7,8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,指明地點\rSpecified place,指明地點\rSpecified place,NaN,指明期間及時段,NaN,須進行檢測日期\r[年年年年-月月-日日]\rRequired testing dates\...,須進行檢測日期
2,NaN,NaN,(視情況而定任何一個,[年年年年-月月-日日],NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,期間及時段),Required testing dates,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,[年年年年-月月-日日],[YYYY-MM-DD],NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Specified date(s),NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,and time period(s),NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,(Any of the specified,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,date(s) and time period(s),NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,as applicable),NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,[YYYY-MM-DD],NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,1.0,佐敦廟街266號地下及\r閣樓九龍咖喱屋\rKowloon Curry House &\rB...,2022-01-03 12:00-14:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-22,NaN,NaN,NaN,NaN
13,NaN,2.0,"銅鑼灣軒尼詩道500號\r希慎廣場11樓美食廣場\rFood Court, 11/F, Hy...",2022-01-03 19:30-21:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-22,NaN,NaN,NaN,NaN

                       0                      1
0  指明地點\rSpecified place  指明地點\rSpecified place

                                                   0        1
0  須進行檢測日期\r[年年年年-月月-日日]\rRequired testing dates\...  須進行檢測日期
1                                       [年年年年-月月-日日]      NaN
2                             Required testing dates      NaN
3                                       [YYYY-MM-DD]      NaN

,0,1,2,3,4,5,6,7
0,NaN,指明地點\rSpecified place,指明地點\rSpecified place,NaN,指明期間及時段,NaN,須進行檢測日期\r[年年年年-月月-日日]\rRequired testing dates\...,須進行檢測日期
1,NaN,(視情況而定任何一個,[年年年年-月月-日日],NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,期間及時段),Required testing dates,NaN,NaN,NaN,NaN
3,NaN,NaN,[年年年年-月月-日日],[YYYY-MM-DD],NaN,NaN,NaN,NaN
4,NaN,NaN,Specified date(s),NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,and time period(s),NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,(Any of the specified,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,date(s) and time period(s),NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,as applicable),NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,[YYYY-MM-DD],NaN,NaN,NaN,NaN,NaN
10,3.0,"銅鑼灣恩平道28 號利\r園二期10樓如新生活體\r驗館\rNUSKINPlaza,10/F...",2022-01-03 18:30-19:30,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-22,NaN,NaN,NaN,NaN
11,4.0,"青衣青敬路33 號青衣\r城一期 3樓 301號鋪肯\r德基\rKFC, Shop 301,...",2022-01-11 07:30-09:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-18\r(...,NaN,NaN,NaN,NaN
12,5.0,"將軍澳唐德街 1 號將軍\r澳廣場 1 樓 1-004 號鋪\r太興\rTaiHing,Sh...",2022-01-10 11:00-12:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-17\r(...,NaN,NaN,NaN,NaN

,0,1,2,3,4,5,6,7,8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,指明地點\rSpecified place,指明地點\rSpecified place,NaN,指明期間及時段,NaN,須進行檢測日期\r[年年年年-月月-日日]\rRequired testing dates\...,須進行檢測日期
2,NaN,NaN,(視情況而定任何一個,[年年年年-月月-日日],NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,期間及時段),Required testing dates,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,[年年年年-月月-日日],[YYYY-MM-DD],NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Specified date(s),NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,and time period(s),NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,(Any of the specified,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,date(s) and time period(s),NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,as applicable),NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,[YYYY-MM-DD],NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,1.0,佐敦廟街266號地下及\r閣樓九龍咖喱屋\rKowloon Curry House &\rB...,2022-01-03 12:00-14:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-22,NaN,NaN,NaN,NaN
13,NaN,2.0,"銅鑼灣軒尼詩道500號\r希慎廣場11樓美食廣場\rFood Court, 11/F, Hy...",2022-01-03 19:30-21:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-22,NaN,NaN,NaN,NaN
14,指明地點\rSpecified place,指明地點\rSpecified place,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,須進行檢測日期\r[年年年年-月月-日日]\rRequired testing dates\...,須進行檢測日期,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,[年年年年-月月-日日],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Required testing dates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,[YYYY-MM-DD],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,指明地點\rSpecified place,指明地點\rSpecified place,NaN,指明期間及時段,NaN,須進行檢測日期\r[年年年年-月月-日日]\rRequired testing dates\...,須進行檢測日期,NaN
20,NaN,(視情況而定任何一個,[年年年年-月月-日日],NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,期間及時段),Required testing dates,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,[年年年年-月月-日日],[YYYY-MM-DD],NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,Specified date(s),NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,and time period(s),NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,(Any of the specified,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,date(s) and time period(s),NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,as applicable),NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,[YYYY-MM-DD],NaN,NaN,NaN,NaN,NaN,NaN
29,3.0,"銅鑼灣恩平道28 號利\r園二期10樓如新生活體\r驗館\rNUSKINPlaza,10/F...",2022-01-03 18:30-19:30,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-22,NaN,NaN,NaN,NaN,NaN
30,4.0,"青衣青敬路33 號青衣\r城一期 3樓 301號鋪肯\r德基\rKFC, Shop 301,...",2022-01-11 07:30-09:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-18\r(...,NaN,NaN,NaN,NaN,NaN
31,5.0,"將軍澳唐德街 1 號將軍\r澳廣場 1 樓 1-004 號鋪\r太興\rTaiHing,Sh...",2022-01-10 11:00-12:00,(1) 2022-01-14 / 2022-01-15\r(2) 2022-01-17\r(...,NaN,NaN,NaN,NaN,NaN

In [16]:
page.apply(lambda y: y if "Specified place" in for val in y.tolist() else None, axis=0)

0    None
1    None
2    None
3    None
4    None
5    None
6    None
7    None
dtype: object

In [4]:
file = "ctn_20220521.pdf"

pages = tabula.read_pdf_with_template(f"cache/{file}", template_path="config/ctn_template.json", lattice=True)

df = pd.DataFrame()
for page in [page for page in pages if page.dropna(how="all").shape[0]]:
    df_merge = page.dropna(how="all") \
        .apply(lambda y: "".join(y.dropna().astype(str)), axis=1) \
        .str.replace(r"\r|\s|’|é|及|或|指明地點|視情況而|年年年年", "", regex=True) \
        .str.extract(r"([^\x00-\x7F]+[\s\d\w\(\)-]{0,}[^\x00-\x7F]+[\s\d\w\(\)-]{0,}[^\x00-\x7F]+[\)]{0,})") \
        .dropna() \
        .set_axis(["specified_place"], axis=1)
    df = pd.concat([df, df_merge], ignore_index=True)

df

   specified_place
0             邨楓樹樓
1              樂生樓
2             邨健曦樓
3              詠興閣
4             邨詠田樓
5             苑旭景閣
6              康蔭樓
7             邨景榆樓
8            花園13座
9              明凱閣
10         曾身處指小時)
11            號嘉信大
12          二)邨華生樓
13            邨瑞喜樓
14           屋邨信義樓
15            邨彩賢樓
16          仙下邨龍昌樓
17             居安樓
18            邨彩善樓
19            邨逸灣樓
20            邨恒欣樓
21             安禧閣
22             平治樓
23            灣畔5座
24            灣畔6座
25            灣畔1座
26          場A座金星閣
27            邨耀興樓
28          二)邨裕興樓
29           灣中心3座
30         曾身處指小時)
31            花園9座
32             雍麗樓
33            邨樂翠樓
34            邨樂泰樓
35            邨樂信樓
36            邨樂誠樓
37           南邨安華樓
38             榮塘樓
39             平信樓
40            花園2座
41            花園8座
42           花園12座
43            花園3座

In [91]:
file = "ctn_20220115.pdf"

pages = tabula.read_pdf_with_template(f"cache/{file}", template_path="ctn_template.json", lattice=True)

df = pd.DataFrame()
for page in [page for page in pages if page.dropna(how="all").shape[0]]:
    df_merge = page.dropna(how="all") \
        .apply(lambda y: "".join(y.dropna().astype(str)), axis=1) \
        .str.replace(r"\r|\s|’|é|及|或|指明地點", "", regex=True) \
        .str.extract(r"([^\x00-\x7F]+[\s\d\w\(\)-]{0,}[^\x00-\x7F]+[\s\d\w\(\)-]{0,}[^\x00-\x7F]+[\)]{0,})") \
        .dropna() \
        .set_axis(["specified_place"], axis=1)
    df = pd.concat([df, df_merge], ignore_index=True)

df

                                  specified_place
0               北角電氣道233號城市花園城市中心商場1樓221至222號鋪大家樂
1                            北角渣華道99號渣華道市政大廈渣華道街市
2                     炮台山英皇道252-264號怡安中心地下23號鋪大快活
3                           天后電氣道143號地鋪東坡豬手麵東坡豬手麵
4                        大坑銅鑼灣道123號D座2樓香港中華游樂會中菜廳
5                             長沙灣幸福邨幸福商場地下1號鋪賓墟餐廳
6                      長沙灣長沙灣道681號貿易廣場地下1樓2號鋪富臨酒家
7                           長沙灣東京街31號恆邦商業大廈1樓肉肉強食
8                         北角電氣道276-280號華凱大廈1樓永勝冰室
9                       西營盤德輔道西358號中亞大樓地下4號鋪大頭蝦餐廳
10                             炮台山電氣道148號地下1號鋪大快活
11                       大嶼山香港國際機場地面運輸候車室機場社區檢測中心
12                    青衣寮肚路6號長亨商場LG1樓115-117號鋪麥當勞
13                            青衣寮肚路6號長亨商場地下長亨鮮薈街市
14                   深水埗白雲街白田社區綜合大樓地下白田社區會堂社區檢測中心
15  大嶼山香港國際機場一號客運大樓4樓鄰近N24登機閘口停機坪香港飛機工程有限公司女職員更衣室
16     大嶼山香港國際機場一號客運大樓4樓鄰近S25登機閘口停機坪香港飛機工程有限公司控制室
17                    大嶼山香港國際機場貨運站香港飛機工程有限公司外勤貨運部
18                    由大角咀(維港灣)開出往機場博覽館路線號碼E21的巴士
19                       由機場博覽館開出往葵芳(南)路線號碼E32的巴士
20                       由葵芳(南)開出往機場博覽館路線號碼E32的巴士

In [3]:
def remove_unrelated_words(wds):
    
    return ''.join([wd for wd in wds if "曾身處指明場" not in wd])

df = df["table_str"].str.extract(r"(\d+\..*[^\x00-\x7F]+)") \
    .dropna() \
    .reset_index(drop=True) \
    .rename(columns={0: "specified_place"})

df = df["specified_place"].str.replace(r"\r|或|及", "", regex=True) \
    .str.findall(r"([^\x00-\x7F]+[\s\d\w\(\)]{0,}[^\x00-\x7F]+[\s\d\w\(\)]{0,}[^\x00-\x7F]+)") \
    .to_frame()

df["specified_place"] = df["specified_place"].map(remove_unrelated_words)

df.head()

  specified_place
0        東涌滿東邨滿順樓
1        上水清河邨清頌樓
2        上水天平邨天明樓
3       秀茂坪寶達邨達怡樓
4       天水圍天澤邨澤潤樓

In [ ]:
df = pd.DataFrame()
for page in pages:
    df = pd.concat([df, page.dropna(how="all")], ignore_index=True)
df

,Unnamed: 0,指明地點\rSpecified place,指明地點\rSpecified place.1,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,"(iii)污水樣本檢測呈陽性的\rPlaces with Sewage Sa\r何曾於以下指明期間及時\r包括但不限於全職、兼職\rfy any persons who had been\rfied date(s) and time period(s)\rime and relief staff, residents a","香港仔南寧街 19號香港仔\r中心港昌閣\rKongCheongCourt,\rAberdeen Centre, 19Nam\rNing Street, Aberdeen6"
0,NaN,筲箕灣工廠街 30號莊士軒\r7號地鋪李偉醫生醫務所\rDr. Lee Wai Clinic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"筲箕灣明華大廈 1座\rTower 1, Ming Wah Dai Ha,\rShau Ke...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,觀塘興業街 23號寶業大廈\r12樓 C室亞美達國際有限\r公司\rArmadaIntern...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,"荃灣沙咀道328 號寶石大\r廈地下 G6-G7號鋪牛奶冰\r室\rMilkCafé,Sho...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,荃灣沙咀道289 號恒生荃\r灣大廈7A 麥廣亮醫生醫\r務所\rDr.MakKwongLe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,紅磡民裕街 41號凱旋工商\r中心第一期二樓 F 室聯寶\r防盜系統有限公司\rUnion ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,紅磡海逸道8 號海逸坊\r1\r樓 101號海逸皇宮大酒樓\rLagunaPalaceRes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,荃灣青山公路398 號愉景\r新城 3樓 3003號鋪鳳城壹\r玖伍肆\rFungShing...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,"荃灣青山道388 號中染大\r廈20樓2008-2011室Certis\rCertis,Un...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,銅鑼灣利園二期23 樓\r2301 室新華三集團有限\r公司\rH3CTechnologie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,灣仔皇后大道東200 號利\r東街地下 G16號鋪金子半\r之助\rKanekoHannos...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,"觀塘興業街 4號 The Wave\r4樓 The Stadium\rTheStadium,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,佐敦上海街 28號恆邦商業\r中心 13 樓 1306 室 Study\rBuddy\rSt...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,佐敦白加士街 56號凱豪商\r業中心地下 1 及 2 鋪譚仔\r雲南米線\rTamJaiYu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,大嶼山赤鱲角暢業路1 號\r機場管理局維修總部\rAirportAuthority\rMai...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,大嶼山赤鱲角香港國際機\r場一號客運大樓離港層\r7\r樓 7T090號鋪 can.teen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,荃灣楊屋道8 號荃灣西如\r心酒店 9樓 Café Circles\rCaféCircles...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,葵涌和宜合道 22號 1樓香\r港聖公會麥理浩夫人中心\rHongKongShengKung...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,"深水埗元州街298D 地下\r西醫杜偉雄醫務所\rDr.ToWaiHungClinic,\r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,"佐敦彌敦道233-239 號佐\r敦薈地下 B鋪土司工坊\rToast Box, Shop ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,"尖沙咀彌敦道222 號恆豐\r酒店\rPrudentialHotel222,\rNathan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,"大嶼山東涌東薈城地下\rG19號鋪星巴克\rStarbucks,UnitG19,G/F,\r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,灣仔駱克道57-73 號粵海\r華 美 灣 際 酒 店 地 庫\rDelaney’s\rDe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,"銅鑼灣軒尼詩道500 號希\r慎廣場 11樓美食廣場\rFoodCourt,11/F,Hys...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,"銅鑼灣記利佐治街6 號香\r港大廈\rHongKongMansion,6\rGreatGeo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,指明地點\rSpecified place,NaN,NaN,指明地點,NaN,NaN,NaN,NaN,NaN
26,Specified place,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,指明地點\rSpecified place,指明地點,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,Specified place,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,"荃灣楊屋道1 號荃新天地\r上層地下 41號鋪 OS Plus\rOS Plus, Shop...",NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,東涌達東路18-20 號東薈\r城名店倉6 樓604 號鋪\rHaagen-Dazs\rHa...,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,東涌達東路18-20 號東薈\r城名店倉 7 樓 704 號鋪食\r代館\rFood Ope...,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,"大嶼山嶼南道貝澳老圍村\r20C號\r20C Pui O Lo Wai Tsuen,\rSo...",NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,"荃灣楊屋道1 號荃新天地\r地下 G30, G32 & G36號鋪\r芽莊\rNha Tra...",NaN,NaN,NaN,NaN,NaN
34,NaN,火炭坳背灣街1-11 號星\r凱.堤岸地盤\rThe Arles Construction ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,"火炭山尾街火炭東熟食市\r場\rFoTanCookedFood\rMarket(East),...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,沙田火炭村60 號地下牛\r屋潮式粉麵\rBeefHouseChiuChow\rNoodle...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,土瓜灣馬頭圍道 23號隆基\r大樓地下 27D-E 號鋪新興\r記茶餐廳\rNew Hing...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,"香港仔南寧街1-5 號香港\r仔中心三期 1樓龍薈\rDragonPlace,1/F,\rA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,"香港仔南寧街9 號香港仔\r中心二期地下\r18, 20-24\r及26 鋪大快活\rFai...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,旺角豉油街60-104B 號鴻\r都大廈地下 9及 10號鋪蘇\r杭冰室2\rJervois...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,香港仔南寧街 19號香港仔\r中心第一期港昌閣(G座)\rKong Cheong Court...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,土瓜灣馬頭涌道 50號工人\r俱樂部 4 樓 404 室工聯會\r職業再訓練中心\rThe ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,尖沙咀廣東道 3-27號海港\r城海運大廈地下OTG02號\r鋪麥奀雲吞麵世家\rMak’s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,美孚美孚新邨第八期百老\r匯街114 號 C2 樓富園海\r鮮酒家\rRichGardenR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,"粉嶺粉嶺名都廣場\r13-17\r號鋪德興茶餐廳\r德興茶餐廳 , Shop 13-17,\...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,美孚美孚新邨荔灣道\r10-\r16號萬事達廣場地下 N51\r號鋪銀龍茶餐廳\rNganL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,葵涌華星街12-14 號華星\r工業大廈14 樓 A 室麗科\r國際控股有限公司\rTopL...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,美孚寶輪街9 號地下新竹\r源越式餐廳\rSun Chuk Yuen Vietnamese\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,"石硤尾石硤尾邨美如樓\rMei Yue House, Shek Kip\rMei Estat...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,"旺角亞皆老街 65號旺角新\r之城 2樓 261號鋪 Kediar\rKediar, Sho...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,"葵青葵涌葵涌邨芊葵樓\rChinKwaiHouse,Kwai\rChung Estate, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,"葵青葵涌葵涌邨綠葵樓\rLukKwaiHouse,Kwai\rChung Estate, K...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,"以北河街、大南街、基隆街\r及桂林街為界,圍繞北河\r街市政大廈對開行人路路\r面\rPav...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,指明地點,NaN,NaN,NaN,NaN,NaN,NaN,指明地點\rSpecified place,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Specified place,NaN
56,指明地點\rSpecified place,NaN,NaN,指明地點,NaN,NaN,NaN,NaN,NaN
57,Specified place,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,"香港仔南寧街 19號香港仔\r中心港昌閣\rKongCheongCourt,\rAberde...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,任何位於附錄圖編號 LIC-\rMIS-374 中劃定區域內的\r大廈或構築物(沒有任何\r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,任何位於附錄圖編號 LIC-\rMIS-375 中劃定區域內的\r大廈或構築物\rAnyof...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,"銅鑼灣利園山道 25-27號\r1樓 I Love Rabbit\rILoveRabbit,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,"旺角通菜街 187號地鋪\rLittle Boss\rLittle Boss, G/F, 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,太子通菜街 142-146號啟\r運大廈地下 C號鋪 Little\rBoss\rLittl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,元朗教育路 87-99號鴻發\r大樓地下 F號鋪 I Love\rRabbit\rI Lov...,NaN,NaN,NaN,NaN,NaN,NaN,NaN